### ISSUE TITLE
Im getting error on railway

### ISSUE THREAD

**Issue by askfriends** [iamLiquidX/SearchX#5]
i have deployed on railway but getting this error in logs

`bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 42, in <module>
    AUTHORIZED_CHATS.add(int(line.split()[0]))
ValueError: invalid literal for int() with base 10: '#Enter'
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 42, in <module>
    AUTHORIZED_CHATS.add(int(line.split()[0]))
ValueError: invalid literal for int() with base 10: '#Enter'
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 42, in <module>
    AUTHORIZED_CHATS.add(int(line.split()[0]))
ValueError: invalid literal for int() with base 10: '#Enter'
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 42, in <module>
    AUTHORIZED_CHATS.add(int(line.split()[0]))
ValueError: invalid literal for int() with base 10: '#Enter'`

**Comment by iamLiquidX** [comment]
Aaahhhh, the python 3.10 ..wait fixing

**Comment by iamLiquidX** [comment]
> i have deployed on railway but getting this error in logs
> 
> `bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8) Traceback (most recent call last): File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details return _get_module_details(pkg_main_name, error) File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details __import__(pkg_name) File "/usr/src/app/bot/__init__.py", line 42, in <module> AUTHORIZED_CHATS.add(int(line.split()[0])) ValueError: invalid literal for int() with base 10: '#Enter' bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8) Traceback (most recent call last): File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details return _get_module_details(pkg_main_name, error) File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details __import__(pkg_name) File "/usr/src/app/bot/__init__.py", line 42, in <module> AUTHORIZED_CHATS.add(int(line.split()[0])) ValueError: invalid literal for int() with base 10: '#Enter' bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8) Traceback (most recent call last): File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details return _get_module_details(pkg_main_name, error) File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details __import__(pkg_name) File "/usr/src/app/bot/__init__.py", line 42, in <module> AUTHORIZED_CHATS.add(int(line.split()[0])) ValueError: invalid literal for int() with base 10: '#Enter' bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8) Traceback (most recent call last): File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details return _get_module_details(pkg_main_name, error) File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details __import__(pkg_name) File "/usr/src/app/bot/__init__.py", line 42, in <module> AUTHORIZED_CHATS.add(int(line.split()[0])) ValueError: invalid literal for int() with base 10: '#Enter'`

Fixed ,Try now. Dont forget to merge latest commit first.
